apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spennende
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 1
  readiness:
    path: isready
    initialDelay: 1
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        name: spennende
        diskAutoresize: true
        diskSize: 10
        diskType: SSD
        tier: {{sqlInstancesTier}}
        databases:
          - name: spennende
  kafka:
    pool: {{kafkaPool}}
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spennende-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_EXTRA_TOPIC
      value: tbd.infotrygd.replikering.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
